import TripForm from "./components/TripForm.jsx";
import Itinerary from "./components/Itinerary.jsx";
import { LoadingState, ErrorState, EmptyState } from "./components/StatePanels.jsx";
import { useTripPlan } from "./hooks/useTripPlan.js";

export default function App() {
  const { status, itinerary, error, run, retry, setItinerary } = useTripPlan();

  return (
    <div className="app-shell">
      <header className="app-header">
        <div className="brand">
          <span className="dot" />
          Waypoint
        </div>
        <h1>Plan a trip in one paragraph.</h1>
        <p>
          Say where you're headed and how you like to travel — pace, budget,
          whatever matters to you. You'll get a day-by-day route back that
          you can rearrange, trim, or dig into.
        </p>
      </header>

      <TripForm onSubmit={run} disabled={status === "loading"} />

      {status === "loading" && <LoadingState />}
      {status === "error" && <ErrorState message={error} onRetry={retry} />}
      {status === "idle" && <EmptyState />}
      {status === "success" && itinerary && (
        <Itinerary
          itinerary={itinerary}
          setItinerary={setItinerary}
          onPlanAnother={() => window.scrollTo({ top: 0, behavior: "smooth" })}
        />
      )}

      <footer className="app-footer">
        <span>built for the frontend internship assignment</span>
        <span>routes generated by AI, worth double-checking before you fly</span>
      </footer>
    </div>
  );
}
